[phases.setup]
nixPkgs = ["php83", "php83Extensions.gd"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"][phases.setup]
nixPkgs = ["php83", "php83Extensions.gd"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]
